-- MySQL Script generated by MySQL Workbench
-- Tue Apr 14 18:13:05 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema nose-covid
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nose-covid
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nose-covid` DEFAULT CHARACTER SET latin1 ;
USE `nose-covid` ;

-- -----------------------------------------------------
-- Table `nose-covid`.`patologia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nose-covid`.`patologia` ;

CREATE TABLE IF NOT EXISTS `nose-covid`.`patologia` (
  `classe` CHAR(8) NOT NULL,
  `description` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`classe`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `nose-covid`.`corba`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nose-covid`.`corba` ;

CREATE TABLE IF NOT EXISTS `nose-covid`.`corba` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `classe` VARCHAR(8) NOT NULL,
  `fs` INT(11) NULL DEFAULT NULL,
  `tf` INT(11) NULL DEFAULT NULL,
  `humyE` DOUBLE(24,21) NULL DEFAULT NULL,
  `tempE` DOUBLE(24,21) NULL DEFAULT NULL,
  `hymytV` DOUBLE(24,21) NULL DEFAULT NULL,
  `tepV` DOUBLE(24,21) NULL DEFAULT NULL,
  `humyS` DOUBLE(24,21) NULL DEFAULT NULL,
  `tempS` DOUBLE(24,21) NULL DEFAULT NULL,
  `data_class` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_corba_patologia1_idx` (`classe` ASC) VISIBLE,
  CONSTRAINT `fk_corba_patologia1`
    FOREIGN KEY (`classe`)
    REFERENCES `nose-covid`.`patologia` (`classe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `nose-covid`.`indicador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nose-covid`.`indicador` ;

CREATE TABLE IF NOT EXISTS `nose-covid`.`indicador` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom_ind` VARCHAR(60) NOT NULL,
  `description` VARCHAR(60) NULL DEFAULT NULL,
  `valor` VARCHAR(16) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nom_ind_UNIQUE` (`nom_ind` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `nose-covid`.`pa_te_ind`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nose-covid`.`pa_te_ind` ;

CREATE TABLE IF NOT EXISTS `nose-covid`.`pa_te_ind` (
  `id_indicador` INT(11) NOT NULL,
  `classe` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id_indicador`, `classe`),
  INDEX `fk_pa_te_ind_patologia1_idx` (`classe` ASC) VISIBLE,
  CONSTRAINT `fk_pa_te_ind_patologia1`
    FOREIGN KEY (`classe`)
    REFERENCES `nose-covid`.`patologia` (`classe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pa_te_ind_indicador1`
    FOREIGN KEY (`id_indicador`)
    REFERENCES `nose-covid`.`indicador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `nose-covid`.`pacient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nose-covid`.`pacient` ;

CREATE TABLE IF NOT EXISTS `nose-covid`.`pacient` (
  `num_hist` CHAR(8) NOT NULL,
  `data_n` DATE NOT NULL,
  PRIMARY KEY (`num_hist`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `nose-covid`.`pa_te_pa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nose-covid`.`pa_te_pa` ;

CREATE TABLE IF NOT EXISTS `nose-covid`.`pa_te_pa` (
  `data` DATETIME NOT NULL,
  `classe` VARCHAR(8) NOT NULL,
  `num_hist` VARCHAR(8) NOT NULL,
  `anotacions` VARCHAR(60) NULL DEFAULT NULL,
  `sexe` ENUM('M', 'F', 'I') NOT NULL,
  PRIMARY KEY (`data`, `classe`, `num_hist`),
  INDEX `fk_pa_te_pa_patologia1_idx` (`classe` ASC) VISIBLE,
  INDEX `fk_pa_te_pa_pacient1_idx` (`num_hist` ASC) VISIBLE,
  CONSTRAINT `fk_pa_te_pa_patologia1`
    FOREIGN KEY (`classe`)
    REFERENCES `nose-covid`.`patologia` (`classe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pa_te_pa_pacient1`
    FOREIGN KEY (`num_hist`)
    REFERENCES `nose-covid`.`pacient` (`num_hist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `nose-covid`.`sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nose-covid`.`sensor` ;

CREATE TABLE IF NOT EXISTS `nose-covid`.`sensor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `position` VARCHAR(45) NOT NULL,
  `lote` DATETIME NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `numbits` INT(11) NULL DEFAULT NULL,
  `time_on` DATETIME NULL DEFAULT NULL,
  `V` DECIMAL(10,0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `nose-covid`.`tipo_sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nose-covid`.`tipo_sensor` ;

CREATE TABLE IF NOT EXISTS `nose-covid`.`tipo_sensor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NULL DEFAULT NULL,
  `RL` FLOAT(8,2) NULL DEFAULT NULL,
  `A` FLOAT(12,9) NULL DEFAULT NULL,
  `alpha` FLOAT(24,21) NULL DEFAULT NULL,
  `description` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `nose-covid`.`sensor_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nose-covid`.`sensor_tipo` ;

CREATE TABLE IF NOT EXISTS `nose-covid`.`sensor_tipo` (
  `id_sensor` INT(11) NOT NULL,
  `id_tipo` INT(11) NOT NULL,
  PRIMARY KEY (`id_sensor`, `id_tipo`),
  INDEX `fk_sensor_tipo_tipo_sensor1_idx` (`id_tipo` ASC) VISIBLE,
  CONSTRAINT `fk_sensor_tipo_tipo_sensor1`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `nose-covid`.`tipo_sensor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sensor_tipo_sensor1`
    FOREIGN KEY (`id_sensor`)
    REFERENCES `nose-covid`.`sensor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `nose-covid`.`th`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nose-covid`.`th` ;

CREATE TABLE IF NOT EXISTS `nose-covid`.`th` (
  `id` INT(11) NOT NULL,
  `A` FLOAT(12,9) NULL DEFAULT NULL,
  `alpha` FLOAT(24,21) NULL DEFAULT NULL,
  `ombrall` INT(11) NULL DEFAULT NULL,
  `afectat` TINYINT(4) NULL DEFAULT NULL,
  `id_sensor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_th_sensor1_idx` (`id_sensor` ASC) VISIBLE,
  CONSTRAINT `fk_th_sensor1`
    FOREIGN KEY (`id_sensor`)
    REFERENCES `nose-covid`.`sensor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `nose-covid`.`vial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nose-covid`.`vial` ;

CREATE TABLE IF NOT EXISTS `nose-covid`.`vial` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `num_vial` TINYINT(4) NOT NULL,
  `prof_sani` VARCHAR(16) NULL DEFAULT NULL,
  `lloc_ext` VARCHAR(60) NULL DEFAULT NULL,
  `num_hist` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vial_pacient1_idx` (`num_hist` ASC) VISIBLE,
  CONSTRAINT `fk_vial_pacient1`
    FOREIGN KEY (`num_hist`)
    REFERENCES `nose-covid`.`pacient` (`num_hist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `nose-covid`.`valor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nose-covid`.`valor` ;

CREATE TABLE IF NOT EXISTS `nose-covid`.`valor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `repticion` TINYINT(4) NOT NULL,
  `orden` INT(11) NOT NULL,
  `valor` FLOAT(24,21) NOT NULL,
  `data` DATETIME NOT NULL,
  `id_vial` INT(11) NOT NULL,
  `id_sensor` INT(11) NOT NULL,
  `id_corba` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_valor_sensor1_idx` (`id_sensor` ASC) VISIBLE,
  INDEX `fk_valor_corba1_idx` (`id_corba` ASC) VISIBLE,
  INDEX `fk_valor_vial1_idx` (`id_vial` ASC) VISIBLE,
  CONSTRAINT `fk_valor_sensor1`
    FOREIGN KEY (`id_sensor`)
    REFERENCES `nose-covid`.`sensor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_valor_corba1`
    FOREIGN KEY (`id_corba`)
    REFERENCES `nose-covid`.`corba` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_valor_vial1`
    FOREIGN KEY (`id_vial`)
    REFERENCES `nose-covid`.`vial` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
